#!/usr/bin/env python
# coding=utf8

from gi.repository import Gtk, GLib

import pkg_resources
import requests


def reset_model():
    model = builder.get_object('classifiers_store')

    model.clear()

    # load data
    url = r'http://pypi.python.org/pypi?%3Aaction=list_classifiers'
    resp = requests.get(url)
    resp.raise_for_status()

    for line in resp.text.splitlines():
        model.append((False, line.strip()))


def on_cell_toggle(renderer, path):
    model = builder.get_object('classifiers_store')
    i = model.get_iter(path)

    # flip column 0, the "active" column
    model.set_value(i, 0, not model.get_value(i, 0))

    # update tree view
    chunks = ['classifiers=[']
    i = model.get_iter_first()
    while i is not None:
        if model.get_value(i, 0) is True:
            chunks.append("    '%s'," % model.get_value(i, 1))
        i = model.iter_next(i)
    chunks.append(']')

    builder.get_object('output').get_buffer().set_text('\n'.join(chunks))


builder = Gtk.Builder()
ui = pkg_resources.resource_string('pypiclassifiers', 'ui.xml').decode('utf8')
builder.add_from_string(ui)

# load data
reset_model()

# set up GUI
mw = builder.get_object('main_window')
mw.connect('delete-event', lambda a, b: Gtk.main_quit())
builder.get_object('renderer_active').connect('toggled', on_cell_toggle)

if '__main__' == __name__:
    GLib.set_application_name('PyPI classifiers selector 0.1')
    mw.show()
    Gtk.main()
